server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEl-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotel/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**
  config:
    import: optional:configserver://http:localhost:8888/

okta:
  oauth2:
    issuer: https://dev-93893425.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaa2rrkj5dMJzHYR5d7
    client-secret: Y2D5oRU4Mm9G3wJSLLfZFWSEtF9dqJPOIfZjfMhl
    scopes: openid, profile, email, offline_access

