#server:
#  port: 8082
#spring:
#  datasource:
#    password: root
#    url: jdbc:mysql://localhost:3306/microservices
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      dialect: org.hibernate.dialect.MySQL5Dialect