server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    password: root
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect

  config:
    import: optional:configserver:http://localhost:8888/




